service:
  web:
    type: NodePort
    port: 8080
    nodePort: 32081
    externalTrafficPolicy: Local

images:
  web:
    repository: ghcr.io/sebrakoczy/skillforge-web
    tag: "604c39f"
  api:
    repository: ghcr.io/sebrakoczy/skillforge-api
    tag: "604c39f"
  worker:
    repository: ghcr.io/sebrakoczy/skillforge-worker
    tag: "604c39f"

postgres:
  password: replace-with-external-secret-or-sealed-secret
  storageClassName: longhorn

redis:
  storageClassName: longhorn


ciliumPolicy:
  enabled: true
  allowedCIDRs:
    - 192.168.1.0/24
