apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: skillforge-api-data
  namespace: skillforge
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
