replicaCount: 2

image:
  repository: 192.168.1.127:5000/my-app
  pullPolicy: Always
  tag: "latest"

serviceAccount:
  create: false
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: false

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}

httpRoute:
  enabled: false
