apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: skillforge
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_GITHUB_ORG/skillforge-ai-interview-portal.git
    targetRevision: main
    path: k8s/overlays/homelab
  destination:
    server: https://kubernetes.default.svc
    namespace: skillforge
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
