apiVersion: v1
kind: Secret
metadata:
  name: skillforge-postgres
  labels:
    {{- include "skillforge.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  DATABASE_URL: {{ printf "postgresql+psycopg2://%s:%s@skillforge-postgres:5432/%s" .Values.postgres.username .Values.postgres.password .Values.postgres.database | quote }}
