apiVersion: v1
kind: ServiceAccount
metadata:
  name: skillforge-api
  labels:
    {{- include "skillforge.labels" . | nindent 4 }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: skillforge-worker
  labels:
    {{- include "skillforge.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.graders.createKubernetesJobs }}
