apiVersion: v1
kind: Service
metadata:
  name: skillforge-web
  labels:
    {{- include "skillforge.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.web.type }}
  {{- if and (eq .Values.service.web.type "NodePort") .Values.service.web.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.web.externalTrafficPolicy }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.service.web.port }}
      targetPort: 8080
      {{- if and (eq .Values.service.web.type "NodePort") .Values.service.web.nodePort }}
      nodePort: {{ .Values.service.web.nodePort }}
      {{- end }}
  selector:
    {{- include "skillforge.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skillforge-web
  labels:
    {{- include "skillforge.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.replicaCount.web }}
  selector:
    matchLabels:
      {{- include "skillforge.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        {{- include "skillforge.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: web
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: web
          image: "{{ .Values.images.web.repository }}:{{ .Values.images.web.tag }}"
          imagePullPolicy: {{ .Values.images.web.pullPolicy }}
          ports:
            - containerPort: 8080
              name: http
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources.web | nindent 12 }}
