apiVersion: apps/v1
kind: Deployment
metadata:
  name: skillforge-api
  namespace: skillforge
spec:
  template:
    spec:
      containers:
        - name: api
          image: ghcr.io/sebrakoczy/skillforge-api:0.2.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skillforge-web
  namespace: skillforge
spec:
  template:
    spec:
      containers:
        - name: web
          image: ghcr.io/sebrakoczy/skillforge-web:0.2.0
