apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins

  sources:
    # 1) The Helm chart (from Helm repo)
    - repoURL: https://charts.jenkins.io
      chart: jenkins
      targetRevision: 5.8.6
      helm:
        valueFiles:
          - $values/platform/jenkins/values.yaml

    # 2) Your Git repo (where values live)
    - repoURL: https://github.com/sebrakoczy/GitOps/tree/main/platform/jenkins
      targetRevision: main
      ref: values

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

