controller:
  persistence:
    enabled: true
    storageClass: longhorn
    size: 20Gi

  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - configuration-as-code

  runAsUser: 1000
  fsGroup: 1000

  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: "2"
      memory: 4Gi

  serviceType: NodePort
  nodePort: 32080

rbac:
  create: true

serviceAccount:
  create: true
  name: jenkins

agent:
  enabled: true
  image: jenkins/inbound-agent
  tag: latest
  resources:
    requests:
      cpu: 200m
      memory: 256Mi

